# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c6d7c3d6c06dcb1787e9b2f9a0111d89c7a6c78095adb53afa5dffd725e7c42eacdcca9f5073ef90bc4359b1f676e76c4ec0bc5e91a468d4d1455f0c06ac8f1

test:
  secret_key_base: 72d7437af84e0dbf4c1ff5143d437a640c9cd06a05800977d3292bb66c78931642ced54950304c8085bf150968c34ed7dd55a9aeb8e67b8358eff83583096757

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
